#! /usr/bin/env bash

release=${1:-v3.3.0post3}

set -e pipefail

docker buildx build \
  -t saladtechnologies/invoke:$release \
  --platform linux/amd64 \
  --output type=docker \
  --provenance false \
  --build-arg RELEASE=$release \
  -f services/invoke/Dockerfile \
  services/invoke

# docker push saladtechnologies/invoke:latest

# docker buildx build \
#   -t saladtechnologies/a1111:ipv6-latest \
#   --platform linux/amd64 \
#   --output type=docker \
#   --provenance false \
#   -f services/AUTOMATIC1111/Dockerfile.ipv6 \
#   services/AUTOMATIC1111

# docker push saladtechnologies/a1111:ipv6-latest
